config/routes.rb
Columbus2::Application.routes.draw do
  resources :tracks
  match 'reverse_geocode/:id' => 'tracks#reverse_geocode', :as => :reverse_geocode

  root :to => 'tracks#index'

end

app/models/track.rb
require 'v900track/v900track'
require 'v900track/v900waypoint'

class Track < ActiveRecord::Base
  has_attached_file :track
  attr_accessible :description, :end_location, :start_location, :title, :track, :start_date, :duration, :distance, :min_speed, :max_speed, :min_height, :max_height

  do_not_validate_attachment_file_type :track
  validates_attachment :track, :presence => true

  after_commit :reverse_geocode, on: :create

  json_serialize :points, gzip: true

  def points(cache=true)
    if self.read_attribute(:points).blank? || !cache
      self.points = to_a
      save
    end
    JSON.parse Zlib::Inflate.inflate(read_attribute(:points))
  end

  def reverse_geocode
    data = points # so that we don't have to parse n times

    update_column(:start_location, Geocoder.address([data.first["lat"],data.first["lon"]]))
    update_column(:end_location, Geocoder.address([data.last["lat"],data.last["lon"]]))

    cache_statistics data
  end

  # store all statistics about a track
  def cache_statistics data
    self.start_date = DateTime.parse data.first["timestamp"]
    self.duration = DateTime.parse(data.last["timestamp"]).to_time - DateTime.parse(data.first["timestamp"]).to_time
    calculate_distance
    self.min_speed = data.map{|p| p["speed"]}.min
    self.max_speed = data.map{|p| p["speed"]}.max
    self.min_height = data.map{|p| p["alt"]}.min
    self.max_height = data.map{|p| p["alt"]}.max
    save
  end

  def distance
    read_attribute(:distance) || calculate_distance
  end

  # import all the files in a specific directory.
  # useful from the command line
  def self.import dir_or_files
    # return an array of absolute pathames (this is why we run map on the dir command
    files = File.directory?(dir_or_files) ? Dir.foreach(dir_or_files).map { |filename| File.join(dir_or_files, filename) } : Dir.glob(dir_or_files)

    files.each do |filename|
      if File.extname(filename).downcase == ".csv" then
        Track.create(:track => File.open(filename, 'rb'))
      end
    end
  end

  private

  def parse_lat str
    str.last == 'N' ? str.to_f : -str.to_f
  end

  def parse_lon str
    str.last == 'E' ? str.to_f : -str.to_f
  end

  def to_a
    data = CSV::read self.track.path, headers: true
    data.map do |p|
      ts = "20#{p['DATE'].scan(/../).join('-')}T#{p['TIME'].scan(/../).join(':')}"
      lat = parse_lat p["LATITUDE N/S"]
      lon = parse_lon p["LONGITUDE E/W"]
      speed = p["SPEED"].to_i
      alt = p["HEIGHT"].to_i
      { timestamp: ts, lat: lat, lon: lon, speed: speed, alt: alt }
    end
  end

  def calculate_distance
    tot = 0
    points.inject(points.first) do |prev,current|
      if prev != current
        tot += Geocoder::Calculations.distance_between([prev["lat"],prev["lon"]], [current["lat"],current["lon"]], :units => :km)
      end
      current
    end
    update_attribute(:distance,tot)
    tot
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  # GET /tracks
  # GET /tracks.json
  def index
    @tracks = Track.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tracks }
    end
  end

  # GET /tracks/1
  # GET /tracks/1.json
  def show
    @track = Track.find(params[:id])

    respond_to do |format|
      format.html
      format.json { render json: @track.points } # we get it raw from the db since it's already JSON serialized
    end
  end

  # GET /tracks/new
  # GET /tracks/new.json
  def new
    @track = Track.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @track }
    end
  end

  # GET /tracks/1/edit
  def edit
    @track = Track.find(params[:id])
  end

  # POST /tracks
  # POST /tracks.json
  def create
    @track = Track.new(params[:track])

    respond_to do |format|
      if @track.save
        format.html { redirect_to @track, notice: 'Track was successfully created.' }
        format.json { render json: @track, status: :created, location: @track }
      else
        format.html { render action: "new" }
        format.json { render json: @track.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tracks/1
  # PUT /tracks/1.json
  def update
    @track = Track.find(params[:id])

    respond_to do |format|
      if @track.update_attributes(params[:track])
        format.html { redirect_to @track, notice: 'Track was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @track.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tracks/1
  # DELETE /tracks/1.json
  def destroy
    @track = Track.find(params[:id])
    @track.destroy

    respond_to do |format|
      format.html { redirect_to tracks_url }
      format.json { head :no_content }
    end
  end

  def reverse_geocode
    @track = Track.find(params[:id])
    @track.reverse_geocode

    respond_to do |format|
      format.html { redirect_to tracks_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # icons!
  def zurb_icon name, tooltip=""
    # manage special cases: we map standard names to specific icons
    # others are managed literally
    icon_name = case name
                when 'Show'      then "fi-eye"
                when 'Duplicate' then "fi-camera"
                when 'Edit'      then "fi-pencil"
                when 'Destroy'   then "fi-x"
                else name
                end
    icon_tooltip = tooltip != "" ? tooltip : name

    "<i id='#{name}' data-tooltip data-options='disable_for_touch:true' title='#{icon_tooltip}' class='#{icon_name}'></i>".html_safe
  end
end

app/helpers/tracks_helper.rb
module TracksHelper
  def basename path
    File.basename path
  end

  def format_duration t
    t ? Time.at(t).utc.strftime("%H:%M:%S") : ""
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Columbus 2" %></title>

    <%= javascript_include_tag "application" %>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= yield %>
    <%= yield :scripts %>
  </body>
</html>

app/views/tracks/_form.html.erb
<%= form_for(@track) do |f| %>
  <% if @track.errors.any? %>
    <div id="error_explanation" class="row">
      <h2><%= pluralize(@track.errors.count, "error") %> prohibited this track from being saved:</h2>

      <ul>
      <% @track.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="large-12 columns">
      <div class="field">
        <%= f.label :title %><br />
        <%= f.text_field :title %>
      </div>
      <div class="field">
        <%= f.label :description %><br />
        <%= f.text_area :description %>
      </div>
      <div class="field">
        <%= f.label :track %><br />
        <%= f.file_field :track %>
      </div>
      <div class="actions">
        <%= f.submit %>
      </div>
    </div>
  </div>
<% end %>

app/views/tracks/_graph.html.erb
<div id="tooltip" style="position: absolute; display: none; border: 1px solid rgb(255, 221, 221); padding: 2px; background-color: rgb(255, 238, 238); opacity: 0.8;"></div>

<%= content_for :scripts do %>
<script type="text/javascript">
$(document).ready(function() {
 var options = {
   series: {
     lines:  { show: true },
     points: { show: true, radius: 2 },
     shadowSize: 0
   },
   xaxis: { mode: "time", timeformat: "%H:%M:%S"},
   yaxes:  [ { }, { position: "right" } ],
   grid: { hoverable: true, clickable: true },
   selection: { mode: "x" }
 };

 var plot = $.plot('#chartdiv',
   [{ label: "Speed",  data: 0 },
   { label: "Height", data: 0, yaxis: 2}],
   options)


 $("#tooltip").css({
   position: "absolute",
   display: "none",
   border: "1px solid #fdd",
   padding: "2px",
   "background-color": "#fee",
   opacity: 0.80
 }).appendTo("body");

 $("#chartdiv").bind("plothover", function (event, pos, item) {
   if (item) {
    var x = item.datapoint[0].toFixed(2), y = item.datapoint[1].toFixed(2);
    var d = new Date(parseInt(x))
    var curr_hour = d.getHours();
    var curr_min = d.getMinutes();
    var curr_sec = d.getSeconds();
    var time = " " + curr_hour + ":" + curr_min + ":" + curr_sec;

    $("#tooltip").html(item.series.label + " at " + time + " = " + y)
    .css({top: item.pageY+5, left: item.pageX+5})
    .fadeIn(200);
  } else {
    $("#tooltip").hide();
  }
});


 $("#chartdiv").bind("plotselected", function (event, ranges) {

   $.each(plot.getXAxes(), function(_, axis) {
    var opts = axis.options;
    opts.min = ranges.xaxis.from;
    opts.max = ranges.xaxis.to;
  });
   plot.setupGrid();
   plot.draw();
   plot.clearSelection();
 });


});
</script>
<% end %>

app/views/tracks/edit.html.erb
<h1>Editing track</h1>

<%= render 'form' %>

<%= link_to 'Show', @track %> |
<%= link_to 'Back', tracks_path %>

app/views/tracks/index.html.erb
<div class="row">
<div class="large-12 columns">
  <h1>Listing tracks</h1>

  <table class="datatable">
    <thead>
      <tr>
        <th>Start Date</th>
        <th>Duration</th>
        <th>Start location</th>
        <th>End location</th>
        <th>Distance (kms)</th>
        <th>Min Speed (km/h)</th>
        <th>Max Speed (km/h)</th>
        <th>Min Height (m)</th>
        <th>Max Height (m)</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @tracks.each do |track| %>
        <tr id='track-<%= track.id %>'>
          <td><%= track.start_date %></td>
          <td><%= format_duration track.duration %></td>
          <td><%= track.start_location %></td>
          <td><%= track.end_location %></td>
          <td><%= track.distance %></td>
          <td><%= track.min_speed %></td>
          <td><%= track.max_speed %></td>
          <td><%= track.min_height %></td>
          <td><%= track.max_height %></td>
          <td>

            <%= link_to zurb_icon('Show'), track %>
            <%= link_to zurb_icon('Edit'), edit_track_path(track) %>
            <%= link_to zurb_icon('fi-compass', 'Reverse Geocode'), reverse_geocode_url(track), remote: true, class: 'reverse-geocode' %>
            <%= link_to zurb_icon('Destroy'), track, method: :delete, data: { confirm: 'Are you sure?' } %>

          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br />

  <%= link_to 'New Track', new_track_path %>
</div>
</div>

app/views/tracks/new.html.erb
<h1>New track</h1>

<%= render 'form' %>

<%= link_to 'Back', tracks_path %>

app/views/tracks/show.html.erb
<div class="row notice">
  <p id="notice"><%= notice %></p>
</div>
<div class="info">
  <div>
    <p>
      <b>Title:</b>
      <%= @track.title %>
    </p>

    <p>
      <b>Description:</b>
      <%= @track.description %>
    </p>

    <p>
      <b>Start location:</b>
      <%= @track.start_location %>
    </p>

    <p>
      <b>End location:</b>
      <%= @track.end_location %>
    </p>

    <p>
      <b>Date:</b>
      <%= @track.start_date %>
    </p>

    <!-- <p>
      <b>End date:</b>
      <%#= @track.end_date %>
    </p> -->

    <p>
      <b>Duration:</b>
      <%= format_duration @track.duration %>
    </p>

    <p>
      <b>Distance:</b>
      <%= number_with_precision(@track.distance, precision: 2) %> km <br />
<!--       (straight: <%#= @data.distance_aerial %> kms) -->
    </p>

<!--     <p>
      <b>Bearing:</b>
      <%#= @data.bearing %>
    </p> -->

    <p>
      <b>Min Speed:</b>
      <%= @track.min_speed %> km/h
    </p>

    <p>
      <b>Max Speed:</b>
      <%= @track.max_speed %> km/h
    </p>

    <p>
      <b>Min Height:</b>
      <%= @track.min_height %> m
    </p>

    <p>
      <b>Max Height:</b>
      <%= @track.max_height %> m
    </p>

    <p>
      <b>Basename:</b>
      <%= link_to basename(@track.track.path), @track.track.url %>
    </p>

    <%= link_to 'Edit', edit_track_path(@track) %> |
    <%= link_to 'Back', tracks_path %>
  </div>
</div>
<div id="map"></div>
<div id="chartdiv"></div>
<div id="tooltip" style="position: absolute; display: none; border: 1px solid rgb(255, 221, 221); padding: 2px; background-color: rgb(255, 238, 238); opacity: 0.8;"></div>

<% content_for :scripts do %>
  <script type="text/javascript">
    $(document).ready(function() {
      // init the map
      var osmLayer      = L.tileLayer('<%= LEAFLET[:osm][:url] %>', {id: 'leaflet-osm', attribution: '<%= LEAFLET[:osm][:attribution] %>'}),
          cycleMapLayer = L.tileLayer('<%= LEAFLET[:cyclemap][:url] %>', {id: 'leaflet-cyclemap', attribution: '<%= LEAFLET[:cyclemap][:attribution] %>'});

      var map = L.map('map', {
        center: [46, 11],
        zoom: 13,
        layers: [osmLayer,cycleMapLayer]
      });

      var layersCtl = { OSM: osmLayer, CycleMap: cycleMapLayer }

      L.control.layers(layersCtl).addTo(map);

      $('#map, #chartdiv').spin({
        shadow: true,
        hwaccel: true
      });
      // load the track
      var track = new Track('<%= track_path(@track, format: :json) %>',map);
      track.addListener('track-loaded',function(){
        $('#map').spin(false);
        track.plot('chartdiv')
        $('#chartdiv').spin(false);
      });
    });
  </script>
<% end %>